### ISSUE TITLE
githubapi: Possible nil pointer dereference panic in convert on commit.HTMLURL.

### ISSUE THREAD

**Issue by dmitshur** [shurcooL/events#1]
I've seen a handful of panics when trying to dereference `*commit.HTMLURL` on line 351:

https://github.com/shurcooL/events/blob/486d915b6997becd25fa35611989ac1e4bab255f/githubapi/githubapi.go#L351

```
2017/10/19 13:12:20 http: panic serving 127.0.0.1:59354: runtime error: invalid memory address or nil pointer dereference
goroutine 183029 [running]:
net/http.(*conn).serve.func1(0xc420ac3220)
	/usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0xa58da0, 0x161df20)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/shurcooL/events/githubapi.convert(0xc421712000, 0x64, 0x8d, 0xc420184120, 0xc420184150, 0x1d5c26, 0xc4201d86a0, 0xa, 0xc4209e02c0, 0x1, ...)
	/gopath/src/github.com/shurcooL/events/githubapi/githubapi.go:351 +0xe21
github.com/shurcooL/events/githubapi.(*service).List(0xc4200c7c00, 0x15e8220, 0xc4209bb740, 0x826, 0x0, 0x0, 0xc42102ac88, 0x57964e)
	/gopath/src/github.com/shurcooL/events/githubapi/githubapi.go:51 +0x148
```

A possible solution is to use `commit.GetHTMLURL()` instead.

However, I want to understand this problem better (how can it happen, how often it's expected to happen) before taking action. This issue is for tracking purposes.

**Comment by dmitshur** [comment]
I have never seen this occur again.

My guess is that this happened because of some temporary problems on GitHub side that shouldn't happen again.

Closing, but can be re-opened and re-considered if it does happen again.
